replicaCount: 2
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
containerPort: 80
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
