apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx
  labels:
    app: web-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      volumes:
        - name: webroot
          emptyDir: {}
      initContainers:
        - name: init-index
          image: busybox:1.36
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - sh
            - -c
            - |
              echo "<html><body><h1>Hola desde $(hostname)</h1><p>Pod: ${POD_NAME}</p></body></html>" > /usr/share/nginx/html/index.html
          volumeMounts:
            - name: webroot
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: webroot
              mountPath: /usr/share/nginx/html
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
